version: "3.3"
services:
  ms-reverse-proxy:
    container_name: ms-reverse-proxy
    build:
      context: ms-reverse-proxy
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=production
    ports:
      - "8080:8080"
    networks:
      - fullstack
    volumes:
      - ./logs/:/logs:rw
    restart: always
    stdin_open: true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    depends_on:
      - "ms-manage-notes"
      - "mc-web"
  ms-manage-notes:
    container_name: ms-manage-notes
    build:
      context: ms-manage-notes
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=production
    ports:
      - "9000:9000"
    networks:
      - fullstack
    volumes:
      - ./logs/:/logs:rw
    restart: always
    stdin_open: true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
  mc-web:
    container_name: mc-web
    build:
      context: mc-web
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=production
    ports:
      - "9005:9005"
    networks:
      - fullstack
    volumes:
      - ./logs/:/logs:rw
    restart: always
    stdin_open: true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
  #web:
  #  container_name: web
  #  build:
  #    context: web
  #    dockerfile: Dockerfile
  #  environment:
  #    - ENVIRONMENT=production
  #  ports:
  #    - "9005:9005"
  #  networks:
  #    - fullstack
  #  volumes:
  #    - ./logs/:/logs:rw
  #    - ./web:/web
  #    - ./web/node_modules
  #    - ./build:/build
  #  restart: always
  #  stdin_open: true
  #  deploy:
  #    restart_policy:
  #      condition: on-failure
  #      delay: 5s
  #      max_attempts: 3
  #      window: 120s
  #    resources:
  #      limits:
  #        cpus: '0.50'
  #        memory: 50M
  #      reservations:
  #        cpus: '0.25'
  #        memory: 20M
  ms-timer-task:
    container_name: ms-timer-task
    build:
      context: ms-timer-task
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=production
    ports:
      - "9010:9010"
    networks:
      - fullstack
    volumes:
      - ./logs/:/logs:rw
    #restart: always
    stdin_open: true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
networks:
  fullstack:
    driver: bridge
